// languages.js

// 1. 语言包数据（移出函数，变为全局可用）
const i18nData = {
    'zh-CN': {
        title: "Future Blockchain Space",
        connect: "连接钱包",
        connected: "已连接",
        total_value: "总资产价值",
        miner_title: "我的矿机",
        miner_name: "FBS 智能矿机 S1",
        buy_miner: "购买矿机",
        pay_fee: "缴纳电费",
        m_count: "数量",
        m_yield: "日产量",
        m_term: "期限",
        m_locked: "锁仓",
        assets_list: "资产概览",
        recharge: "充值",
        withdraw: "提币",
        exchange: "兑换",
        team_title: "我的团队",
        invite_code: "邀请码",
        inviter: "推荐人",
        direct_num: "直推人数",
        direct_sales: "直推业绩",
        team_num: "团队人数",
        team_sales: "团队业绩",
        total_rewards: "累计奖励",
        copy_addr: "复制地址",
        confirm_pay: "立即支付",
        balance: "余额",
        input_amount: "输入数量",
        history_title: "交易历史",
        transfer_title: "转账流水",
        loading: "加载中...",
        no_data: "暂无数据",
        // 新增状态与类型
        已提交: "已提交",
        处理中: "处理中",
        成功: "成功",
        失败: "失败",
        充值: "充值",
        提币: "提币",
        兑换: "兑换",
        购买矿机: "购买矿机",
        缴纳电费: "缴纳电费",
        SYSTEM: "系统操作",
        transfer: "转账",
        internal_transfer: "内部转账",
        receiver_address: "接收者钱包地址",
        select_token: "选择代币",
        transfer_amount: "转账数量",
        confirm_transfer: "确认转账",
        available_balance: "可用",
        transfer_request_submitted: "转账请求已提交",
        insufficient_balance: "余额不足！当前余额为 ",
        invalid_address: "请输入正确的钱包地址",
        enter_amount: "请输入转账数量",
    },
    'zh-TW': {
        title: "Future Blockchain Space",
        connect: "連接錢包",
        connected: "已連接",
        total_value: "總資產價值",
        miner_title: "我的礦機",
        miner_name: "FBS 智能礦機 S1",
        buy_miner: "購買礦機",
        pay_fee: "繳納電費",
        m_count: "數量",
        m_yield: "日產量",
        m_term: "期限",
        m_locked: "鎖倉",
        assets_list: "資產概覽",
        recharge: "充值",
        withdraw: "提幣",
        exchange: "兌換",
        team_title: "我的團隊",
        invite_code: "邀請碼",
        inviter: "推薦人",
        direct_num: "直推人數",
        direct_sales: "直推業績",
        team_num: "團隊人數",
        team_sales: "團隊業績",
        total_rewards: "累計獎勵",
        history_title: "交易歷史",
        copy_addr: "複製地址",
        confirm_pay: "立即支付",
        balance: "餘額",
        input_amount: "輸入數量",
        transfer_title: "轉賬流水",
        loading: "載入中...",
        no_data: "暫無數據",
        // 新增状态与类型
        "已提交": "已提交",
        "处理中": "處理中",
        "成功": "成功",
        "失败": "失敗",
        "充值": "充值",
        "提币": "提幣",
        "兑换": "兌換",
        "购买矿机": "購買礦機",
        "缴纳电费": "繳納電費",
        "SYSTEM": "系統操作"
    },
    'en': {
        title: "Future Blockchain Space",
        connect: "Connect Wallet",
        connected: "Connected",
        total_value: "Total Net Assets",
        miner_title: "My Miner",
        miner_name: "FBS Smart Miner S1",
        buy_miner: "Buy Miner",
        pay_fee: "Pay Electricity",
        m_count: "Quantity",
        m_yield: "Daily Yield",
        m_term: "Term",
        m_locked: "Locked",
        assets_list: "Assets Overview",
        recharge: "Deposit",
        withdraw: "Withdraw",
        exchange: "Exchange",
        team_title: "My Team",
        invite_code: "Invite Code",
        inviter: "Inviter",
        direct_num: "Direct Referrals",
        direct_sales: "Direct Sales",
        team_num: "Team Size",
        team_sales: "Team Sales",
        total_rewards: "Total Rewards",
        history_title: "History",
        copy_addr: "Copy Address",
        confirm_pay: "Pay Now",
        balance: "Balance",
        input_amount: "Enter Amount",
        transfer_title: "Transfer Logs",
        loading: "Loading...",
        no_data: "No Data",
        // 新增状态与类型
        "已提交": "Submitted",
        "处理中": "Processing",
        "成功": "Success",
        "失败": "Failed",
        "充值": "Deposit",
        "提币": "Withdraw",
        "兑换": "Exchange",
        "购买矿机": "Buy Miner",
        "缴纳电费": "Electricity Fee",
        "SYSTEM": "System"
    },
    'ja': {
        title: "Future Blockchain Space",
        connect: "ウォレット接続",
        connected: "接続済み",
        total_value: "総資産価値",
        miner_title: "マイニングマシン",
        miner_name: "FBS スマートマイナー S1",
        buy_miner: "マシン購入",
        pay_fee: "電気代支払い",
        m_count: "保有数",
        m_yield: "日次収益",
        m_term: "期限",
        m_locked: "ロック中",
        assets_list: "資産一覧",
        recharge: "入金",
        withdraw: "出金",
        exchange: "交換",
        team_title: "マイチーム",
        invite_code: "招待コード",
        inviter: "紹介者",
        direct_num: "直紹介人数",
        direct_sales: "直紹介実績",
        team_num: "チーム人数",
        team_sales: "チーム実績",
        total_rewards: "累計報酬",
        history_title: "履歴",
        copy_addr: "アドレスコピー",
        confirm_pay: "今すぐ支払う",
        balance: "残高",
        input_amount: "数量入力",
        transfer_title: "転送ログ",
        loading: "読み込み中...",
        no_data: "データなし",
        // 新增状态与类型
        "已提交": "送信済み",
        "处理中": "処理中",
        "成功": "成功",
        "失败": "失敗",
        "充值": "入金",
        "提币": "出金",
        "兑换": "交換",
        "购买矿机": "マイナー購入",
        "缴纳电费": "電気代支払い",
        "SYSTEM": "システム"
    },
    'ko': {
        title: "Future Blockchain Space",
        connect: "지갑 연결",
        connected: "연결됨",
        total_value: "총 자산 가치",
        miner_title: "나의 채굴기",
        miner_name: "FBS 스마트 마이너 S1",
        buy_miner: "채굴기 구매",
        pay_fee: "전기료 납부",
        m_count: "수량",
        m_yield: "일일 생산량",
        m_term: "기간",
        m_locked: "잠금",
        assets_list: "자산 현황",
        recharge: "충전",
        withdraw: "출금",
        exchange: "환전",
        team_title: "나의 팀",
        invite_code: "초대 코드",
        inviter: "추천인",
        direct_num: "직속 추천",
        direct_sales: "직속 실적",
        team_num: "팀 인원",
        team_sales: "팀 실적",
        total_rewards: "누적 보상",
        history_title: "거래 내역",
        copy_addr: "주소 복사",
        confirm_pay: "결제하기",
        balance: "잔액",
        input_amount: "수량 입력",
        transfer_title: "이체 기록",
        loading: "로딩 중...",
        no_data: "데이터 없음",
        // 新增状态与类型
        "已提交": "제출됨",
        "处理中": "처리 중",
        "成功": "성공",
        "失败": "실패",
        "充值": "입금",
        "提币": "출금",
        "兑换": "환전",
        "购买矿机": "채굴기 구매",
        "缴纳电费": "전기료 납부",
        "SYSTEM": "시스템"
    },
    'ru': {
        title: "Future Blockchain Space",
        connect: "Подключить",
        connected: "Подключено",
        total_value: "Общая стоимость",
        miner_title: "Мой майнер",
        miner_name: "FBS Smart Miner S1",
        buy_miner: "Купить майнер",
        pay_fee: "Оплатить свет",
        m_count: "Количество",
        m_yield: "Доход в день",
        m_term: "Срок",
        m_locked: "Заблокировано",
        assets_list: "Список активов",
        recharge: "Депозит",
        withdraw: "Вывод",
        exchange: "Обмен",
        team_title: "Моя команда",
        invite_code: "Инвайт-код",
        inviter: "Пригласитель",
        direct_num: "Личные",
        direct_sales: "Личные продажи",
        team_num: "Размер команды",
        team_sales: "Продажи команды",
        total_rewards: "Всего наград",
        history_title: "История",
        copy_addr: "Копировать",
        confirm_pay: "Оплатить",
        balance: "Баланс",
        input_amount: "Введите сумму",
        transfer_title: "Журнал переводов",
        loading: "Загрузка...",
        no_data: "Нет данных",
        // 新增状态与类型
        "已提交": "Отправлено",
        "处理中": "В процессе",
        "成功": "Успешно",
        "失败": "Ошибка",
        "充值": "Депозит",
        "提币": "Вывод",
        "兑换": "Обмен",
        "购买矿机": "Покупка майнера",
        "缴纳电费": "Оплата эл-ии",
        "SYSTEM": "Система"
    }
};

// 2. 渲染函数（执行翻译的核心）
window.i18nRender = function() {
    const lang = localStorage.getItem('fbs_lang') || 'zh-CN';
    const dict = i18nData[lang];
    if (!dict) return;

    // 寻找所有标记了 data-i18n 属性的 HTML 元素
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (dict[key]) {
            // 如果是输入框，修改 placeholder；否则修改文本内容
            if (el.tagName === 'INPUT') {
                el.placeholder = dict[key];
            } else {
                el.innerText = dict[key];
            }
        }
    });
};

// 3. 切换语言函数
window.switchLang = function(lang) {
    console.log("切换语言至:", lang);
    localStorage.setItem('fbs_lang', lang);
    window.i18nRender(); // 切换后立即重绘页面
};

// 4. 初始化
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('fbs_lang') || 'zh-CN';
    const selectEl = document.getElementById('langSelect');
    if (selectEl) selectEl.value = savedLang;
    window.i18nRender();
});
