
// 1. 语言包数据（移出函数，变为全局可用）
const i18nData = {
    'zh-CN': {
        title: "NEO生态挖矿矩阵",
        connect: "连接钱包",
        connected: "已连接",
        total_value: "总资产价值",
        miner_title: "我的矿机",
        miner_name: "阿瓦隆 1066 智能矿机",
        miner_desc: "每台矿机算力≈30TH/s，功耗：1500W",
        buy_miner: "购买矿机",
        pay_fee: "缴纳电费",
        m_count: "数量",
        m_yield: "日产量",
        m_term: "期限",
        m_locked: "锁仓",
        assets_list: "资产概览",
        recharge: "充值",
        withdraw: "提币",
        exchange: "兑换",
        team_title: "我的团队",
        invite_code: "邀请码",
        inviter: "推荐人",
        direct_num: "直推人数",
        direct_sales: "直推业绩",
        team_num: "团队人数",
        team_sales: "团队业绩",
        total_rewards: "累计奖励",
        copy_addr: "复制地址",
        confirm_pay: "立即支付",
        balance: "余额",
        input_amount: "输入数量",
        history_title: "交易历史",
        transfer_title: "转账流水",
        loading: "加载中...",
        no_data: "暂无数据",
        // 状态与类型匹配 (Key 不可改)
        已提交: "已提交",
        处理中: "处理中",
        成功: "成功",
        失败: "失败",
        充值: "充值",
        提币: "提币",
        兑换: "兑换",
        购买矿机: "购买矿机",
        缴纳电费: "缴纳电费",
        SYSTEM: "系统操作",
        transfer: "转账",
        internal_transfer: "内部转账",
        receiver_address: "接收者钱包地址",
        select_token: "选择代币",
        transfer_amount: "转账数量",
        confirm_transfer: "确认转账",
        available_balance: "可用",
        transfer_request_submitted: "转账请求已提交",
        insufficient_balance: "余额不足！当前余额为 ",
        invalid_address: "请输入正确的钱包地址",
        enter_amount: "请输入转账数量",
        btn_bind_inviter: "绑定我的推荐人",
        modal_bind_title: "绑定推荐关系",
        placeholder_inviter_id: "请输入推荐人 ID",
        bind_success: "绑定成功",
        bind_loading: "正在提交...",
        btn_confirm: "确认提交",
        nav_market: "看板",
        nav_whitepaper: "白皮书",
        nav_bitget: "排行榜",
        nav_explorer: "BSC 浏览器",
        nav_community: "常用社区",
        copy_success: "已成功复制到剪贴板",
        copy_fail: "复制失败，请手动操作",
        wait_audit: "申请已提交，等待审核",
        nav_home: "首页",
        nav_mine: "矿场",
        nav_market: "看板",
        nav_me: "我的",
        news_title: "公告与新闻",
        news_list: [
            "NEO生态挖矿矩阵正式上线，开启算力新纪元",
            "FBS 协议 v2.0 升级完成，交易损耗降低 30%",
            "关于 NEO 节点维护的临时公告（3月30日）",
            "新功能：支持一键提取 10 种生态代币收益",
            "全球节点招募计划火热进行中，立即参与"
        ],
        stats_title: "代币详情与参数",
        stats_subtitle: "代币经济学与市场数据",
        token_labels: {
            fullname: "全称",
            position: "定位",
            supply: "总供应量",
            distribution: "分配机制",
            mechanism: "释放机制"
        },
        tokens: [
            { symbol: "NEO", name: "New Energy Ore", desc: "生态核心主币 / 挖矿核心产出", total: "1,000,000,000", dist: "挖矿产出 30% | 生态建设 20% | 团队激励 15% (锁2年) | 早期投资 15% | 社区空投 10% | 流动性 10%", mech: "挖矿线性产出，预计5年内挖完，逐年减半。" },
            { symbol: "NEX", name: "Neo Energy Xtreme", desc: "算力加速 / 挖矿增益凭证", total: "500,000,000", dist: "高性能节点挖矿 40% | 质押NEO获得 25% | 生态合作 15% | 团队 10% | 社区激励 10%", mech: "随算力提升逐步释放，高算力节点优先产出。" },
            { symbol: "NET", name: "Neo Energy Token", desc: "网络燃料 / Gas 费代币", total: "200,000,000", dist: "节点运行奖励 35% | 网络维护 30% | 流动性储备 20% | 社区空投 15%", mech: "燃烧+销毁机制，总量通缩。" },
            { symbol: "NEA", name: "Neo Energy Asset", desc: "算力资产映射 / 实体矿机锚定币", total: "动态锚定实体算力规模", dist: "实体矿机映射 60% | 算力质押挖矿 25% | 生态合作 10% | 团队 5%", mech: "按算力接入量分批铸造，资产与实体算力一一对应。" },
            { symbol: "NRY", name: "Neo Resource Yield", desc: "收益分红 / 生态利润权益", total: "300,000,000", dist: "生态利润分红 50% | 长期持有奖励 25% | 节点贡献激励 15% | 团队储备 10%", mech: "按季度利润分配，持有即可分红，鼓励长期锁仓。" },
            { symbol: "NCL", name: "Neo Core Link", desc: "跨链枢纽 / 生态互通媒介", total: "400,000,000", dist: "跨链节点奖励 40% | 生态合作 30% | 社区治理 15% | 团队开发 15%", mech: "跨链交互、协议对接时逐步释放。" }
        ]
    },
    'zh-HK': {
        title: "NEO生態挖礦矩陣",
        connect: "連接錢包",
        connected: "已連接",
        total_value: "總資產價值",
        miner_title: "我的礦機",
        miner_name: "阿瓦隆 1066 智慧礦機",
        miner_desc: "每台礦機算力≈30TH/s，耗電量：1500W",
        buy_miner: "購買礦機",
        pay_fee: "繳納電費",
        m_count: "數量",
        m_yield: "日產量",
        m_term: "期限",
        m_locked: "鎖倉",
        assets_list: "資產概覽",
        recharge: "充值",
        withdraw: "提幣",
        exchange: "兌換",
        team_title: "我的團隊",
        invite_code: "邀請碼",
        inviter: "推薦人",
        direct_num: "直推人數",
        direct_sales: "直推業績",
        team_num: "團隊人數",
        team_sales: "團隊業績",
        total_rewards: "累計獎勵",
        copy_addr: "複製地址",
        confirm_pay: "立即支付",
        balance: "餘額",
        input_amount: "輸入數量",
        history_title: "交易歷史",
        transfer_title: "轉帳流水",
        loading: "加載中...",
        no_data: "暫無數據",
        已提交: "已提交",
        处理中: "處理中",
        成功: "成功",
        失败: "失敗",
        充值: "充值",
        提币: "提幣",
        兑换: "兌換",
        购买矿机: "購買礦機",
        缴纳电费: "繳納電費",
        SYSTEM: "系統操作",
        transfer: "轉帳",
        internal_transfer: "內部轉帳",
        receiver_address: "接收者錢包地址",
        select_token: "選擇代幣",
        transfer_amount: "轉帳數量",
        confirm_transfer: "確認轉帳",
        available_balance: "可用",
        transfer_request_submitted: "轉帳請求已提交",
        insufficient_balance: "餘額不足！當前餘額為 ",
        invalid_address: "請輸入正確的錢包地址",
        enter_amount: "請輸入轉帳數量",
        btn_bind_inviter: "綁定我的推薦人",
        modal_bind_title: "綁定推薦關係",
        placeholder_inviter_id: "請輸入推薦人 ID",
        bind_success: "綁定成功",
        bind_loading: "正在提交...",
        btn_confirm: "確認提交",
        nav_market: "看板",
  nav_whitepaper: "白皮書",
  nav_bitget: "排行榜",
  nav_explorer: "BSC 瀏覽器",
  nav_community: "常用社區",
  copy_success: "已成功複製到剪貼板",
  copy_fail: "複製失敗，請手動操作",
  wait_audit: "申請已提交，等待審核",
        nav_home: "首頁",
        nav_mine: "礦場",
        nav_market: "看板",
        nav_me: "我的",
        news_title: "公告與新聞",
        news_list: [
            "NEO生態挖礦矩陣正式上線，開啟算力新紀元",
            "FBS 協議 v2.0 升級完成，交易損耗降低 30%",
            "關於 NEO 節點維護的臨時公告（3月30日）",
            "新功能：支持一鍵提取 10 種生態代幣收益",
            "全球節點招募計劃火熱進行中，立即參與"
        ],
        stats_title: "代幣詳情與參數",
        stats_subtitle: "代幣經濟學與市場數據",
        token_labels: {
            fullname: "全稱",
            position: "定位",
            supply: "總供應量",
            distribution: "分配機制",
            mechanism: "釋放機制"
        },
        tokens: [
            { symbol: "NEO", name: "New Energy Ore", desc: "生態核心主幣 / 挖礦核心產出", total: "1,000,000,000", dist: "挖礦產出 30% | 生態建設 20% | 團隊激勵 15% (鎖2年) | 早期投資 15% | 社區空投 10% | 流動性 10%", mech: "挖礦線性產出，預計5年內挖完，逐年減半。" },
            { symbol: "NEX", name: "Neo Energy Xtreme", desc: "算力加速 / 挖礦增益憑證", total: "500,000,000", dist: "高性能節點挖礦 40% | 質押NEO獲得 25% | 生態合作 15% | 團隊 10% | 社區激勵 10%", mech: "隨算力提升逐步釋放，高算力節點優先產出。" },
            { symbol: "NET", name: "Neo Energy Token", desc: "網絡燃料 / Gas 費代幣", total: "200,000,000", dist: "節點運行獎勵 35% | 網絡維護 30% | 流動性儲備 20% | 社區空投 15%", mech: "燃燒+銷毀機制，總量通縮。" },
            { symbol: "NEA", name: "Neo Energy Asset", desc: "算力資產映射 / 實體礦機錨定幣", total: "動態錨定實體算力規模", dist: "實體礦機映射 60% | 算力質押挖礦 25% | 生態合作 10% | 團隊 5%", mech: "按算力接入量分批鑄造，資產與實體算力一一對應。" },
            { symbol: "NRY", name: "Neo Resource Yield", desc: "收益分紅 / 生態利潤權益", total: "300,000,000", dist: "生態利潤分紅 50% | 長期持有獎勵 25% | 節點貢獻激勵 15% | 團隊儲備 10%", mech: "按季度利潤分配，持有即可分紅，鼓勵長期鎖倉。" },
            { symbol: "NCL", name: "Neo Core Link", desc: "跨鏈樞紐 / 生態互通媒介", total: "400,000,000", dist: "跨鏈節點獎勵 40% | 生態合作 30% | 社區治理 15% | 團隊開發 15%", mech: "跨鏈交互、協議對接時逐步釋放。" }
        ]
    },
    'en': {
        title: "NEO Ecological Mining Matrix",
        connect: "Connect Wallet",
        connected: "Connected",
        total_value: "Total Asset Value",
        miner_title: "My Miners",
        miner_name: "Avalon 1066 Smart Miner",
        miner_desc: "Each mining rig has a hash rate of approximately 30 TH/s and a power consumption of 1500W..",
        buy_miner: "Buy Miner",
        pay_fee: "Pay Electricity",
        m_count: "Count",
        m_yield: "Daily Yield",
        m_term: "Term",
        m_locked: "Locked",
        assets_list: "Assets Overview",
        recharge: "Recharge",
        withdraw: "Withdraw",
        exchange: "Exchange",
        team_title: "My Team",
        invite_code: "Invite Code",
        inviter: "Inviter",
        direct_num: "Direct Referrals",
        direct_sales: "Direct Sales",
        team_num: "Team Size",
        team_sales: "Team Sales",
        total_rewards: "Total Rewards",
        copy_addr: "Copy Addr",
        confirm_pay: "Pay Now",
        balance: "Balance",
        input_amount: "Enter Amount",
        history_title: "History",
        transfer_title: "Transfers",
        loading: "Loading...",
        no_data: "No Data",
        已提交: "Submitted",
        处理中: "Processing",
        成功: "Success",
        失败: "Failed",
        充值: "Recharge",
        提币: "Withdraw",
        兑换: "Exchange",
        购买矿机: "Buy Miner",
        缴纳电费: "Electricity Fee",
        SYSTEM: "System Operation",
        transfer: "Transfer",
        internal_transfer: "Internal Transfer",
        receiver_address: "Receiver Address",
        select_token: "Select Token",
        transfer_amount: "Amount",
        confirm_transfer: "Confirm Transfer",
        available_balance: "Available",
        transfer_request_submitted: "Transfer request submitted",
        insufficient_balance: "Insufficient balance! Current is ",
        invalid_address: "Please enter a valid address",
        enter_amount: "Please enter transfer amount",
        btn_bind_inviter: "Bind My Inviter",
        modal_bind_title: "Bind Relationship",
        placeholder_inviter_id: "Enter Inviter ID",
        bind_success: "Bound Successfully",
        bind_loading: "Submitting...",
        btn_confirm: "Confirm",
        nav_market: "Dashboard",
  nav_whitepaper: "Whitepaper",
  nav_bitget: "Leaderboard",
  nav_explorer: "BSC Explorer",
  nav_community: "Community",
  copy_success: "Copied to clipboard",
  copy_fail: "Copy failed, please do it manually",
  wait_audit: "Submitted, waiting for audit",
        nav_home: "Home",
        nav_mine: "Mining",
        nav_market: "Market",
        nav_me: "Profile",
        news_title: "Announcements",
        news_list: [
            "NEO Mining Matrix is officially live!",
            "FBS Protocol v2.0 upgrade completed, gas fees reduced by 30%.",
            "Temporary notice on NEO node maintenance (Mar 30).",
            "New Feature: One-click withdrawal for 10 ecosystem tokens.",
            "Global Node Recruitment Program is ongoing. Join now!"
        ],
        stats_title: "Token Details",
        stats_subtitle: "Tokenomics & Market Data",
        token_labels: {
            fullname: "Full Name",
            position: "Position",
            supply: "Total Supply",
            distribution: "Distribution",
            mechanism: "Release Mechanism"
        },
        tokens: [
            { symbol: "NEO", name: "New Energy Ore", desc: "Core Ecosystem Token / Mining Output", total: "1,000,000,000", dist: "Mining 30% | Eco 20% | Team 15% (2y lock) | Investors 15% | Airdrop 10% | Liquidity 10%", mech: "Linear mining output, 5-year cycle with annual halving." },
            { symbol: "NEX", name: "Neo Energy Xtreme", desc: "Hashrate Booster / Mining Voucher", total: "500,000,000", dist: "Node Mining 40% | NEO Staking 25% | Eco-Partners 15% | Team 10% | Community 10%", mech: "Released gradually as total hashrate increases." },
            { symbol: "NET", name: "Neo Energy Token", desc: "Network Fuel / Gas Token", total: "200,000,000", dist: "Node Rewards 35% | Maintenance 30% | Liquidity 20% | Airdrop 15%", mech: "Burn & Deflationary mechanism via network usage." },
            { symbol: "NEA", name: "Neo Energy Asset", desc: "Asset Mapping / Hardware Anchored", total: "Anchored to Physical Hashrate", dist: "Hardware Mapping 60% | Staking 25% | Eco 10% | Team 5%", mech: "Minted based on physical hashrate integration." },
            { symbol: "NRY", name: "Neo Resource Yield", desc: "Dividend / Profit Rights", total: "300,000,000", dist: "Profit Sharing 50% | Long-term Holders 25% | Node Incentives 15% | Reserves 10%", mech: "Quarterly profit distribution for stakers." },
            { symbol: "NCL", name: "Neo Core Link", desc: "Cross-chain Hub / Interop Media", total: "400,000,000", dist: "Cross-chain Node 40% | Eco-Technical 30% | Governance 15% | Dev 15%", mech: "Released via cross-chain interaction & protocol usage." }
        ]
    },
    'ja': {
        title: "NEO生態鉱業マトリックス",
        connect: "ウォレット接続",
        connected: "接続済み",
        total_value: "総資産価値",
        miner_title: "マイニング機",
        miner_name: "アバロン1066スマートマイナー",
        miner_desc: "各マイニングリグのハッシュレートは約30TH/s、消費電力は1500Wです。",
        buy_miner: "購入する",
        pay_fee: "電気代支払い",
        m_count: "数量",
        m_yield: "日産量",
        m_term: "期間",
        m_locked: "ロック",
        assets_list: "資産概要",
        recharge: "チャージ",
        withdraw: "出金",
        exchange: "交換",
        team_title: "マイチーム",
        invite_code: "招待コード",
        inviter: "紹介者",
        direct_num: "直紹介人数",
        direct_sales: "直紹介実績",
        team_num: "チーム人数",
        team_sales: "チーム実績",
        total_rewards: "累計報酬",
        copy_addr: "アドレスコピー",
        confirm_pay: "今すぐ支払う",
        balance: "残高",
        input_amount: "数量入力",
        history_title: "取引履歴",
        transfer_title: "振込履歴",
        loading: "読み込み中...",
        no_data: "データなし",
        已提交: "提出済み",
        处理中: "処理中",
        成功: "成功",
        失败: "失敗",
        充值: "チャージ",
        提币: "出金",
        兑换: "交換",
        购买矿机: "機体購入",
        缴纳电费: "電気代",
        SYSTEM: "システム操作",
        transfer: "送金",
        internal_transfer: "内部送金",
        receiver_address: "受取人アドレス",
        select_token: "トークン選択",
        transfer_amount: "送金数量",
        confirm_transfer: "送金確認",
        available_balance: "利用可能",
        transfer_request_submitted: "送金リクエスト送信済み",
        insufficient_balance: "残高不足！現在の残高は ",
        invalid_address: "有効なアドレスを入力してください",
        enter_amount: "送金数量を入力してください",
        btn_bind_inviter: "紹介者を紐付け",
        modal_bind_title: "紹介関係の紐付け",
        placeholder_inviter_id: "紹介者IDを入力してください",
        bind_success: "紐付けに成功しました",
        bind_loading: "提出中...",
        btn_confirm: "確認",
        nav_market: "ダッシュボード",
  nav_whitepaper: "ホワイトペーパー",
  nav_bitget: "ランキング",
  nav_explorer: "BSCエクスプローラー",
  nav_community: "コミュニティ",
  copy_success: "クリップボードにコピーしました",
  copy_fail: "コピーに失敗しました。手動で行ってください",
  wait_audit: "申請が送信されました。審査待ちです",
        nav_home: "ホーム",
        nav_mine: "マイニング",
        nav_market: "ボード",
        nav_me: "マイページ",
        news_title: "お知らせとニュース",
        news_list: [
            "NEOエコマイニングマトリックスが正式に稼働開始！",
            "FBSプロトコルv2.0へのアップグレード完了、手数料30%削減。",
            "NEOノードメンテナンスに関する臨時のお知らせ（3月30日）。",
            "新機能：10種類のトークン報酬を一括受取可能に。",
            "グローバルノード募集中、今すぐご参加ください！"
        ],
        stats_title: "トークンの詳細",
        stats_subtitle: "トークノミクスと市場データ",
        token_labels: {
            fullname: "フルネーム",
            position: "役割",
            supply: "総供給量",
            distribution: "配分",
            mechanism: "リリース"
        },
        tokens: [
            { symbol: "NEO", name: "New Energy Ore", desc: "エコシステム基軸通貨 / マイニング報酬", total: "1,000,000,000", dist: "マイニング 30% | エコ 20% | チーム 15% (2年ロック) | 投資家 15% | エアドロップ 10% | 流動性 10%", mech: "5年間の線形マイニング出力、毎年半減。" },
            { symbol: "NEX", name: "Neo Energy Xtreme", desc: "ハッシュレート加速 / マイニング証明", total: "500,000,000", dist: "ノード報酬 40% | NEOステーキング 25% | 提携 15% | チーム 10% | コミュニティ 10%", mech: "ハッシュレートの向上に応じて段階的にリリース。" },
            { symbol: "NET", name: "Neo Energy Token", desc: "ネットワーク燃料 / Gasトークン", total: "200,000,000", dist: "ノード報酬 35% | メンテナンス 30% | 流動性 20% | エアドロップ 15%", mech: "バーンおよびデフレメカニズム。" },
            { symbol: "NEA", name: "Neo Energy Asset", desc: "資産マッピング / 実機マイナー固定", total: "実機ハッシュレートにペッグ", dist: "マッピング 60% | ステーキング 25% | エコ 10% | チーム 5%", mech: "物理的なハッシュレートの接続に応じて鋳造。" },
            { symbol: "NRY", name: "Neo Resource Yield", desc: "収益配当 / エコシステム利益権", total: "300,000,000", dist: "収益配分 50% | 長期保有者 25% | ノード貢献 15% | チーム 10%", mech: "四半期ごとの利益分配、長期ロック推奨。" },
            { symbol: "NCL", name: "Neo Core Link", desc: "クロスチェーンハブ / 相互運用", total: "400,000,000", dist: "ノード報酬 40% | 技術提携 30% | ガバナンス 15% | 開発 15%", mech: "クロスチェーン利用時に段階的にリリース。" }
        ]
    },
    'ko': {
        title: "NEO 생태 채굴 매트릭스",
        connect: "지갑 연결",
        connected: "연결됨",
        total_value: "총 자산 가치",
        miner_title: "나의 채굴기",
        miner_name: "아발론 1066 스마트 마이너",
        miner_desc: "각 채굴 장비는 약 30 TH/s의 해시레이트와 1500W의 전력 소비량을 가지고 있습니다.",
        buy_miner: "채굴기 구매",
        pay_fee: "전기료 납부",
        m_count: "수량",
        m_yield: "일일 생산량",
        m_term: "기간",
        m_locked: "잠금",
        assets_list: "자산 개요",
        recharge: "충전",
        withdraw: "출금",
        exchange: "환전",
        team_title: "나의 팀",
        invite_code: "초대 코드",
        inviter: "추천인",
        direct_num: "직속 인원",
        direct_sales: "직속 실적",
        team_num: "팀 인원",
        team_sales: "팀 실적",
        total_rewards: "누적 보상",
        copy_addr: "주소 복사",
        confirm_pay: "즉시 결제",
        balance: "잔액",
        input_amount: "수량 입력",
        history_title: "거래 내역",
        transfer_title: "이체 내역",
        loading: "로딩 중...",
        no_data: "데이터 없음",
        已提交: "제출됨",
        处理中: "처리 중",
        成功: "성공",
        失败: "실패",
        充值: "충전",
        提币: "출금",
        兑换: "환전",
        购买矿机: "채굴기 구매",
        缴纳电费: "전기료 납부",
        SYSTEM: "시스템 작업",
        transfer: "이체",
        internal_transfer: "내부 이체",
        receiver_address: "수신자 주소",
        select_token: "토큰 선택",
        transfer_amount: "이체 수량",
        confirm_transfer: "이체 확인",
        available_balance: "사용 가능",
        transfer_request_submitted: "이체 요청이 제출되었습니다",
        insufficient_balance: "잔액 부족! 현재 잔액은 ",
        invalid_address: "올바른 지갑 주소를 입력하세요",
        enter_amount: "이체 수량을 입력하세요",
        btn_bind_inviter: "추천인 바인딩",
        modal_bind_title: "추천 관계 바인딩",
        placeholder_inviter_id: "추천인 ID를 입력하세요",
        bind_success: "바인딩 성공",
        bind_loading: "제출 중...",
        btn_confirm: "확인",
        nav_market: "대시보드",
  nav_whitepaper: "백서",
  nav_bitget: "랭킹",
  nav_explorer: "BSC 탐색기",
  nav_community: "커뮤니티",
  copy_success: "클립보드에 복사되었습니다",
  copy_fail: "복사 실패, 수동으로 시도하십시오",
  wait_audit: "신청이 제출되었습니다. 심사 대기 중입니다",
        nav_home: "홈",
        nav_mine: "광산",
        nav_market: "대시보드",
        nav_me: "내 정보",
        news_title: "공지 및 뉴스",
        news_list: [
            "NEO 에코 마이닝 매트릭스 정식 출시, 새로운 시대 개막!",
            "FBS 프로토콜 v2.0 업그레이드 완료, 수수료 30% 절감.",
            "NEO 노드 점검에 관한 임시 공지 (3월 30일).",
            "신기능: 10종 생태계 토큰 수익 일괄 수령 지원.",
            "글로벌 노드 모집 중, 지금 바로 참여하세요!"
        ],
        stats_title: "토큰 상세 정보",
        stats_subtitle: "토큰코노믹스 및 시장 데이터",
        token_labels: {
            fullname: "전체 이름",
            position: "역할",
            supply: "총 공급량",
            distribution: "배분",
            mechanism: "해제 메커니즘"
        },
        tokens: [
            { symbol: "NEO", name: "New Energy Ore", desc: "생태계 핵심 통화 / 채굴 산출물", total: "1,000,000,000", dist: "채굴 30% | 생태계 20% | 팀 15% (2년 락업) | 투자자 15% | 에어드랍 10% | 유동성 10%", mech: "5년 선형 채굴 산출, 매년 반감기 적용." },
            { symbol: "NEX", name: "Neo Energy Xtreme", desc: "해시레이트 가속 / 채굴 증빙", total: "500,000,000", dist: "노드 채굴 40% | NEO 스테이킹 25% | 파트너십 15% | 팀 10% | 커뮤니티 10%", mech: "해시레이트 증가에 따라 점진적 해제." },
            { symbol: "NET", name: "Neo Energy Token", desc: "네트워크 연료 / Gas 토큰", total: "200,000,000", dist: "노드 보상 35% | 유지보수 30% | 유동성 20% | 에어드랍 15%", mech: "소각 및 디플레이션 메커니즘." },
            { symbol: "NEA", name: "Neo Energy Asset", desc: "자산 매핑 / 하드웨어 앵커링", total: "물리적 해시레이트에 고정", dist: "하드웨어 매핑 60% | 스테이킹 25% | 파트너십 10% | 팀 5%", mech: "물리적 해시레이트 유입에 따른 발행." },
            { symbol: "NRY", name: "Neo Resource Yield", desc: "수익 배당 / 생태계 이익 권리", total: "300,000,000", dist: "수익 공유 50% | 장기 홀더 25% | 노드 기여 15% | 팀 10%", mech: "분기별 수익 분배, 장기 스테이킹 권장." },
            { symbol: "NCL", name: "Neo Core Link", desc: "크로스체인 허브 / 상호운용 매체", total: "400,000,000", dist: "노드 보상 40% | 기술 협력 30% | 거버넌스 15% | 개발 15%", mech: "크로스체인 상호작용 시 점진적 해제." }
        ]
    },
    'ru': {
        title: "Экологическая матрица добычи полезных ископаемых NEO",
        connect: "Подключить кошелек",
        connected: "Подключено",
        total_value: "Общая стоимость активов",
        miner_title: "Мои майнеры",
        miner_name: "Умный майнер Avalon 1066",
        miner_desc: "Каждая майнинговая установка имеет хешрейт приблизительно 30 TH/s и потребляет 1500 Вт.",
        buy_miner: "Купить майнер",
        pay_fee: "Оплатить эл-во",
        m_count: "Кол-во",
        m_yield: "Доход в день",
        m_term: "Срок",
        m_locked: "Заблокировано",
        assets_list: "Обзор активов",
        recharge: "Пополнить",
        withdraw: "Вывод",
        exchange: "Обмен",
        team_title: "Моя команда",
        invite_code: "Код приглашения",
        inviter: "Пригласитель",
        direct_num: "Личные рефералы",
        direct_sales: "Личные продажи",
        team_num: "Размер команды",
        team_sales: "Продажи команды",
        total_rewards: "Всего наград",
        copy_addr: "Копировать адрес",
        confirm_pay: "Оплатить сейчас",
        balance: "Баланс",
        input_amount: "Введите сумму",
        history_title: "История транзакций",
        transfer_title: "История переводов",
        loading: "Загрузка...",
        no_data: "Нет данных",
        已提交: "Отправлено",
        处理中: "В обработке",
        成功: "Успешно",
        失败: "Ошибка",
        充值: "Пополнение",
        提币: "Вывод",
        兑换: "Обмен",
        购买矿机: "Покупка майнера",
        缴纳电费: "Оплата эл-ва",
        SYSTEM: "Системная операция",
        transfer: "Перевод",
        internal_transfer: "Внутренний перевод",
        receiver_address: "Адрес получателя",
        select_token: "Выберите токен",
        transfer_amount: "Сумма перевода",
        confirm_transfer: "Подтвердить перевод",
        available_balance: "Доступно",
        transfer_request_submitted: "Запрос на перевод отправлен",
        insufficient_balance: "Недостаточно средств! Текущий баланс: ",
        invalid_address: "Введите корректный адрес кошелька",
        enter_amount: "Введите сумму перевода",
        btn_bind_inviter: "Привязать пригласителя",
        modal_bind_title: "Привязка отношений",
        placeholder_inviter_id: "Введите ID пригласителя",
        bind_success: "Привязка успешно завершена",
        bind_loading: "Отправка...",
        btn_confirm: "Подтвердить",
        nav_market: "Панель",
  nav_whitepaper: "Белая книга",
  nav_bitget: "Рейтинг",
  nav_explorer: "BSC Проводник",
  nav_community: "Сообщество",
  copy_success: "Скопировано в буфер обмена",
  copy_fail: "Ошибка копирования, скопируйте вручную",
  wait_audit: "Заявка подана, ожидается проверка",
        nav_home: "Главная",
        nav_mine: "Майнинг",
        nav_market: "Рынок",
        nav_me: "Профиль",
        news_title: "Объявления и новости",
        news_list: [
            "Матрица майнинга NEO официально запущена!",
            "Протокол FBS v2.0 обновлен, затраты снижены на 30%.",
            "Временное уведомление о техническом обслуживании узлов NEO (30 марта).",
            "Новая функция: Вывод 10 видов токенов одним нажатием.",
            "Глобальная программа набора узлов в разгаре. Присоединяйтесь!"
        ],
        stats_title: "Детали токена",
        stats_subtitle: "Токеномика и рыночные данные",
        token_labels: {
            fullname: "Полное имя",
            position: "Позиция",
            supply: "Общее предложение",
            distribution: "Распределение",
            mechanism: "Механизм выпуска"
        },
        tokens: [
            { symbol: "NEO", name: "New Energy Ore", desc: "Ядро экосистемы / Результат майнинга", total: "1,000,000,000", dist: "Майнинг 30% | Экосистема 20% | Команда 15% (лок 2г) | Инвесторы 15% | Аирдроп 10% | Ликвидность 10%", mech: "Линейный майнинг на 5 лет с ежегодным сокращением." },
            { symbol: "NEX", name: "Neo Energy Xtreme", desc: "Ускоритель хешрейта / Ваучер майнинга", total: "500,000,000", dist: "Майнинг нод 40% | Стейкинг NEO 25% | Партнеры 15% | Команда 10% | Сообщество 10%", mech: "Выпуск по мере роста общей мощности сети." },
            { symbol: "NET", name: "Neo Energy Token", desc: "Топливо сети / Gas токен", total: "200,000,000", dist: "Награды нод 35% | Обслуживание 30% | Резерв 20% | Аирдроп 15%", mech: "Сжигание и дефляционный механизм." },
            { symbol: "NEA", name: "Neo Energy Asset", desc: "Маппинг активов / Привязка к оборудованию", total: "Привязка к физической мощности", dist: "Маппинг оборудования 60% | Стейкинг 25% | Партнеры 10% | Команда 5%", mech: "Минтинг на основе подключенной физической мощности." },
            { symbol: "NRY", name: "Neo Resource Yield", desc: "Дивиденды / Права на прибыль", total: "300,000,000", dist: "Доля прибыли 50% | Холдеры 25% | Инсентивы нод 15% | Резервы 10%", mech: "Ежеквартальное распределение прибыли." },
            { symbol: "NCL", name: "Neo Core Link", desc: "Кроссчейн-хаб / Взаимодействие", total: "400,000,000", dist: "Кроссчейн ноды 40% | Тех-партнеры 30% | Управление 15% | Разработка 15%", mech: "Выпуск при кроссчейн-взаимодействии." }
        ]
    }
};

// 2. 渲染函数（执行翻译的核心）
window.i18nRender = function() {
    // 统一获取当前语言
    const lang = localStorage.getItem('fbs_lang') || 'zh-CN';
    const dict = i18nData[lang];
    if (!dict) return;

    // A. 翻译所有静态标记了 data-i18n 属性的元素
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (dict[key]) {
            if (el.tagName === 'INPUT') {
                el.placeholder = dict[key];
            } else {
                el.innerText = dict[key];
            }
        }
    });

    // B. 【关键新增】执行动态内容的渲染
    // 这样切换语言时，新闻和看板数据会同步重新生成
    if (typeof renderNews === 'function') {
        renderNews(lang);
    }
    
    if (typeof renderStatsPage === 'function') {
        renderStatsPage(lang);
    }
};

// 3. 切换语言函数 (保持不变)
window.switchLang = function(lang) {
    console.log("切换语言至:", lang);
    localStorage.setItem('fbs_lang', lang);
    window.i18nRender(); 
};

// 4. 初始化 (保持不变)
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('fbs_lang') || 'zh-CN';
    const selectEl = document.getElementById('langSelect');
    if (selectEl) selectEl.value = savedLang;
    window.i18nRender();
});
